In [12]:
import pandas as pd

In [45]:
path = "COVID19VaccDosesAdministered_AKL10_w.csv"

In [46]:
df_impf1 = pd.read_csv(path)

## Nur jüngstes Datum

In [47]:
df_Mai = df_impf1[df_impf1["date"] == 202117]
df_Mai

,date,geoRegion,altersklasse_covid19,entries,type_variant,pop,sumTotal,per100Persons,per100Persons_mean7d,per100PersonsTotal,mean7d,type,version,granularity,freq,prct
18,202117,AI,0 - 9,0.0,altersklasse_covid19,1763,0.0,0.00,NaN,0.00,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,detailed,0.000,0.0
37,202117,AI,10 - 19,3.0,altersklasse_covid19,1642,7.0,0.18,NaN,0.43,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,detailed,0.003,0.3
56,202117,AI,20 - 29,19.0,altersklasse_covid19,2104,74.0,0.90,NaN,3.52,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,detailed,0.017,1.7
75,202117,AI,30 - 39,49.0,altersklasse_covid19,2008,109.0,2.44,NaN,5.43,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,detailed,0.045,4.5
94,202117,AI,40 - 49,89.0,altersklasse_covid19,2002,272.0,4.45,NaN,13.59,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,detailed,0.082,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,202117,CHFL,40 - 49,NaN,altersklasse_covid19,894191,NaN,3.52,5.11,16.29,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,partial,0.113,11.3
3758,202117,CHFL,50 - 59,NaN,altersklasse_covid19,942694,NaN,6.90,5.80,28.10,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,partial,0.234,23.4
3759,202117,CHFL,60 - 69,NaN,altersklasse_covid19,686738,NaN,11.41,NaN,57.61,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,partial,0.281,28.1
3760,202117,CHFL,70 - 79,NaN,altersklasse_covid19,532606,NaN,9.87,NaN,113.28,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,partial,0.189,18.9
3761,202117,CHFL,80+,NaN,altersklasse_covid19,341184,NaN,5.14,NaN,139.09,NaN,COVID19VaccDosesAdministered,2021-05-04_09-13-52,partial,0.063,6.3

In [48]:
#grosse Kantone rausfiltern
df_MaiGross = df_Mai[(df_Mai["geoRegion"] == "ZH") | (df_Mai["geoRegion"] == "VD") | (df_Mai["geoRegion"] == "BE")]

In [49]:
df_Mai.columns

Index(['date', 'geoRegion', 'altersklasse_covid19', 'entries', 'type_variant',
       'pop', 'sumTotal', 'per100Persons', 'per100Persons_mean7d',
       'per100PersonsTotal', 'mean7d', 'type', 'version', 'granularity',
       'freq', 'prct'],
      dtype='object')

In [50]:
# weglöschen der unnötigen Zahlen
df_MaiGross = df_MaiGross.drop(['type', 'version', 'granularity',
       'freq', 'prct'], axis = 1)

In [51]:
df_MaiGross

,date,geoRegion,altersklasse_covid19,entries,type_variant,pop,sumTotal,per100Persons,per100Persons_mean7d,per100PersonsTotal,mean7d
360,202117,BE,0 - 9,2.0,altersklasse_covid19,101287,5.0,0.00,NaN,0.00,NaN
379,202117,BE,10 - 19,468.0,altersklasse_covid19,96454,1828.0,0.49,NaN,1.90,NaN
398,202117,BE,20 - 29,2593.0,altersklasse_covid19,119810,10700.0,2.16,NaN,8.93,NaN
417,202117,BE,30 - 39,4436.0,altersklasse_covid19,141448,16451.0,3.14,NaN,11.63,NaN
436,202117,BE,40 - 49,7125.0,altersklasse_covid19,137708,22582.0,5.17,NaN,16.40,NaN
455,202117,BE,50 - 59,13442.0,altersklasse_covid19,156601,39564.0,8.58,NaN,25.26,NaN
474,202117,BE,60 - 69,13998.0,altersklasse_covid19,125570,63295.0,11.15,NaN,50.41,NaN
493,202117,BE,70 - 79,8080.0,altersklasse_covid19,99066,109752.0,8.16,NaN,110.79,NaN
512,202117,BE,80+,3451.0,altersklasse_covid19,61530,85727.0,5.61,NaN,139.33,NaN
2925,202117,VD,0 - 9,1.0,altersklasse_covid19,86781,1.0,0.00,NaN,0.00,NaN
2944,202117,VD,10 - 19,248.0,altersklasse_covid19,89543,761.0,0.28,NaN,0.85,NaN
2963,202117,VD,20 - 29,2363.0,altersklasse_covid19,105425,8478.0,2.24,NaN,8.04,NaN
2982,202117,VD,30 - 39,2859.0,altersklasse_covid19,116644,12862.0,2.45,NaN,11.03,NaN
3001,202117,VD,40 - 49,4228.0,altersklasse_covid19,117016,18658.0,3.61,NaN,15.94,NaN
3020,202117,VD,50 - 59,13044.0,altersklasse_covid19,113315,42456.0,11.51,NaN,37.47,NaN
3039,202117,VD,60 - 69,8790.0,altersklasse_covid19,77560,47017.0,11.33,NaN,60.62,NaN
3058,202117,VD,70 - 79,4742.0,altersklasse_covid19,60455,74792.0,7.84,NaN,123.72,NaN
3077,202117,VD,80+,1682.0,altersklasse_covid19,38359,53610.0,4.38,NaN,139.76,NaN
3267,202117,ZH,0 - 9,0.0,altersklasse_covid19,162354,93.0,0.00,NaN,0.06,NaN
3286,202117,ZH,10 - 19,271.0,altersklasse_covid19,141741,1917.0,0.19,NaN,1.35,NaN
3305,202117,ZH,20 - 29,2054.0,altersklasse_covid19,187257,14038.0,1.10,NaN,7.50,NaN
3324,202117,ZH,30 - 39,3394.0,altersklasse_covid19,253964,23979.0,1.34,NaN,9.44,NaN
3343,202117,ZH,40 - 49,5319.0,altersklasse_covid19,228236,32441.0,2.33,NaN,14.21,NaN
3362,202117,ZH,50 - 59,10191.0,altersklasse_covid19,220632,53506.0,4.62,NaN,24.25,NaN
3381,202117,ZH,60 - 69,15377.0,altersklasse_covid19,151391,76751.0,10.16,NaN,50.70,NaN
3400,202117,ZH,70 - 79,12139.0,altersklasse_covid19,118213,105480.0,10.27,NaN,89.23,NaN
3419,202117,ZH,80+,4772.0,altersklasse_covid19,75487,94746.0,6.32,NaN,125.51,NaN

In [54]:
#Seit Kampagnenanfang
df_pivot = df_MaiGross.pivot(index='altersklasse_covid19', columns = "geoRegion", values = "per100PersonsTotal")
df_pivot

geoRegion                 BE      VD      ZH
altersklasse_covid19
0 - 9                   0.00    0.00    0.06
10 - 19                 1.90    0.85    1.35
20 - 29                 8.93    8.04    7.50
30 - 39                11.63   11.03    9.44
40 - 49                16.40   15.94   14.21
50 - 59                25.26   37.47   24.25
60 - 69                50.41   60.62   50.70
70 - 79               110.79  123.72   89.23
80+                   139.33  139.76  125.51

In [55]:
df_pivot2 = df_MaiGross.pivot(index='altersklasse_covid19', columns = "geoRegion", values = "per100Persons")
df_pivot2

geoRegion                BE     VD     ZH
altersklasse_covid19
0 - 9                  0.00   0.00   0.00
10 - 19                0.49   0.28   0.19
20 - 29                2.16   2.24   1.10
30 - 39                3.14   2.45   1.34
40 - 49                5.17   3.61   2.33
50 - 59                8.58  11.51   4.62
60 - 69               11.15  11.33  10.16
70 - 79                8.16   7.84  10.27
80+                    5.61   4.38   6.32

In [59]:
#Exportieren Excel
df_MaiGross.to_excel("1_verimpfte_dosen_0401.xlsx")